# Generated by Django 3.2.25 on 2025-02-19 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='ID de la orden')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Fallido'), (2, 'Completado')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orden fallida',
                'verbose_name_plural': 'Órdenes fallidas',
            },
        ),
    ]
