# Generated by Django 3.2.25 on 2025-03-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedorder',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje'),
        ),
    ]
