# Generated by Django 6.0.3 on 2026-04-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactcache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedorder',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Fallido'), (2, 'Completado')], db_index=True, default=1, verbose_name='Estado'),
        ),
    ]
