# Generated by Django 6.0.3 on 2026-06-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_index_failedorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RucCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='RUC')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón social')),
                ('checked_at', models.DateTimeField(verbose_name='Última consulta exitosa a la API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Caché de RUC',
                'verbose_name_plural': 'Cachés de RUC',
            },
        ),
    ]
