# Generated by Django 6.0.3 on 2026-08-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ruccache'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cajero', 'Cajero POS'), ('pos_sin_mapeo', 'Regla: cualquier otro cajero POS'), ('web', 'Regla: órdenes web')], db_index=True, default='cajero', max_length=20, verbose_name='Tipo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, help_text='Cargá el email o el ID; el integrador completa el otro contra WooCommerce.', max_length=254, verbose_name='Email del cajero en WordPress')),
                ('wp_user_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID del cajero en WordPress')),
                ('bims_posale_id', models.PositiveIntegerField(blank=True, help_text='Vacío = no facturar las órdenes de esta sucursal.', null=True, verbose_name='Punto de venta en BIMS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ('tipo', 'nombre'),
            },
        ),
    ]
