# Generated by Django 6.0.3 on 2026-08-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sembrar_sucursales'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedorder',
            name='bims_invoice_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Nº de factura'),
        ),
        migrations.AddField(
            model_name='failedorder',
            name='bims_sale_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='ID de venta en BIMS'),
        ),
    ]
