# Generated by Django 5.2.17 on 2026-09-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_estado_pausada'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Clase de alerta')),
                ('sent_at', models.DateTimeField(verbose_name='Último aviso enviado')),
            ],
            options={
                'verbose_name': 'Silencio de alerta',
                'verbose_name_plural': 'Silencios de alerta',
            },
        ),
    ]
